.travis.yml
CHANGELOG.md
README.md

Related to #14 
Tests seem to be passing just fine with wagtail 1.5.3 in Python 3.4 & 3.5.
Python 3.3 failed, because of the wagtail dependency automatically using Django 1.9, which needs `find_spec` to get going (which wasn't added until Python 3.4)
Tests on wagtail versions 1.5.1 and 1.5.2 failed because of the `html5lib` bug (fixed by 1.5.3), so those tests have been removed.

Adds automated travis CI tests for Python 3.4 and 3.5

---

wagtailmenus/models.py
wagtailmenus/templatetags/menu_tags.py
wagtailmenus/tests/settings.py

Added `modify_submenu_items` method to `MenuPage`, which is used in `sub_menu` and `section_menu` tags to make additions to a list of `menu_items`, in a way that is easy to extend/override to meet custom needs (as outlined in #6)

Move 'addition of extra menu items' logic to `MenuPage` model

---

CHANGELOG.md
wagtailmenus/templatetags/menu_tags.py
wagtailmenus/tests/fixtures/test.json
wagtailmenus/tests/test_frontend.py

* Supply `prime_menu_items` with `request.path`, which will be compared with non-page-link menu items to check if they should have the `active` class applied to them.
* Add test to show the active class applying correctly when viewing a custom URL
Fixes #38

Apply `active` to custom url links if currently at that URL

---

CHANGELOG.md
wagtailmenus/migrations/0012_auto_20160419_0039.py
wagtailmenus/models.py

The use of binary strings in a wagtailmenus migration are causing some environments to detect changes in wagtailmenus and attempt to create a new migration. This fix doctors the old migration to replace the binary strings with regular python strings, and also wraps the help_text for the problematic field for translation (likely to be the original cause)

Fix for #52 (migration issue)

---

CHANGELOG.md
README.md
wagtailmenus/app_settings.py
wagtailmenus/context_processors.py
wagtailmenus/managers.py
wagtailmenus/models.py
wagtailmenus/panels.py
wagtailmenus/settings/base.py
wagtailmenus/templatetags/menu_tags.py
wagtailmenus/tests/test_backend.py
wagtailmenus/views.py
wagtailmenus/wagtail_hooks.py

- Added a `wagtailmenus` context processor to add reliable values to context
- Removed untidy/hacky patching functionality from `get_attrs_from_context()`
- Added a setting to toggle tree position matching on request path on and off
- Updated installation instructions in README and added note for the new `WAGTAILMENUS_GUESS_TREE_POSITION_FROM_PATH` setting

Create a context_processor to handle filling of missing data

---

CHANGELOG.md
wagtailmenus/models.py
wagtailmenus/static/wagtailmenus/css/menu-edit.css
wagtailmenus/templates/wagtailmenus/mainmenu_edit.html
wagtailmenus/views.py
wagtailmenus/wagtail_hooks.py

Relates to issue #63.
Improves the readability of the forms by right-aligning labels and tweeking the width of labels/fields/formsets slightly.
Flat Menu edit:
Main Menu edit:

Add some override styles to the form pages to improve layout of fields

---

wagtailmenus/__init__.py
wagtailmenus/apps.py

Using AppConfig to properly initialize the global var app_settings, so we don't do imports when a `pip install` loads `__init__.py` to read the `__version__` string. 
Fix for https://github.com/rkhleics/wagtailmenus/issues/93

Prevent imports occurring during pip install

---

README.md

"Defining flat menus in the CMS" is now the second entry in the "Using wagtailmenus" section, while "Using the {% main_menu %} tag" is now the third.

Switch position of two headings in README.

---

wagtailmenus/app_settings.py

Make AppSettings module fetch project settings on initialisation and save a reference to it, instead of reimporting every time a setting value is requested. Seems to be working okay locally, and tests that modify settings before requesting app settings values also seem to be working okay (which has been the biggest issue so far)

Optimisations for AppSettings module

---

README.md
wagtailmenus/models/__init__.py
wagtailmenus/models/pages.py

Move all with fields and methods from `MenuPage` to a new abstract `MenuPageMixin` model, which can be used in cases where `MenuPage` cannot be used.

Make it easier to use MenuPage fields and methods when already subclassing a Page model

---

.travis.yml
README.md
requirements/development.txt
tox.ini

Tests pass without any changes needed, and no warnings triggered - so this essentially just adds a new environment test to the Travis config to ensure support is maintained.

Support for Wagtail 1.10 and Django 1.11

---

wagtailmenus/context_processors.py
wagtailmenus/utils/misc.py
wagtailmenus/utils/template.py

- Minor code tidying in utils.misc
- Make context_processors.wagtailmenus use a default site when site isn’t populated on request

Use default site in context_processors if request.site hasn't been set

---

wagtailmenus/models/menuitems.py
wagtailmenus/tests/test_models.py

Fixes #123. 
Since wagtail is still in the process of making updates to support non-field errors, and there's no telling if the recent changes apply to InlinePanel model errors too, I thought it made sense to just raise field errors instead.

Fix for: #123 Error not visible when missing both link page and link url

---

wagtailmenus/templatetags/menu_tags.py
wagtailmenus/tests/models/pages.py

Corrects an issue introduced by PR #121.
If `has_submenu_items` or `modify_submenu_items` do accept a `request` parameter, we don't try again without it: The 2nd attempt needs to happen within the `except` block, not after. 
Also updates the test models so that the warning is no longer given when running tests

Fix try/except logic for calling modify_submenu_items and has_submenu_items with/without request

---

wagtailmenus/templatetags/menu_tags.py
wagtailmenus/utils/misc.py

This is a remnant of when that function used to attempt to guess tree position, but for a while, that responsibility has fallen soley on the context_process, so that the work is only ever done once.

Remove needless passing of 'guess_tree_position' to utils.get_attrs_from_context

---

runtests.py
wagtailmenus/models/pages.py
wagtailmenus/templatetags/menu_tags.py
wagtailmenus/tests/models/pages.py
wagtailmenus/utils/deprecation.py
wagtailmenus/utils/inspection.py

Fixes #131
As well as the problem outlined in the above issue, using TypeError in a try/except isn't acceptable, as it incorrectly swallows TypeError exceptions raised elsewhere.
Changes include:
- Modifies ‘runtests’ to accept a ‘deprecation’ argument that can be used to optionally surface deprecation warnings in tests
- Adds some wagtailmenus-specific deprecation warnings to wagtailmenus.utils.deprecation to be used within the project
- Adds `wagtailmenus.utils.inspection` with the `accepts_kwarg()` method to help with the current method argument deprecation situation
- Use internal deprecation warning classes and ‘accepts_kwargs’ to the deprecation stuff currently in place for handling the addition of the `request` keyword to several methods

Fix: Implement a better solution for deprecation errors

---

.travis.yml
README.md
requirements/development.txt
tox.ini

- Test configuration tweaks to test against Wagtail 1.11 and Django 1.11
- Update development requirements for easier manual testing
- No other changes needed (no compatibility issues found)

Wagtail 1.11 support

---

wagtailmenus/models/pages.py

Should fix #152 
In addition to the above, also this PR also does the following:
- Adds better code commenting to the method to help explain what's
- Abstract out the logic to identify text to use for a 'repeated menu item' to a new 'get_text_for_repeated_item' method to make it more convenient to override, and also to respect the `WAGTAILMENUS_PAGE_FIELD_FOR_MENU_ITEM_TEXT` setting instead of just defaulting to the page title
- Minor code tidying (Flake 8 bit)

Always set 'has_children_in_menu=False' on repeated menu items by default

---

wagtailmenus/models/menuitems.py

To make the workings a little clearer, and also to better handle situations where an instance without link_text or link_page (even if we prevent that with validation, data can always be changed via other routes)

Tidy 'menu_text' method on AbstractMenuItem

---

CONTRIBUTORS.md
docs/source/overview.rst
docs/source/releases/2.5.0a.rst
docs/source/releases/index.rst
wagtailmenus/__init__.py
wagtailmenus/models/pages.py
wagtailmenus/templatetags/menu_tags.py
wagtailmenus/utils/deprecation.py

- Version bump to 2.5a0
- Remove fallback handling of 'modify_submenu_items' methods with no 'request' kwarg
- Remove fallback handling of 'has_submenu_items' methods with no 'request' kwarg
- Remove fallback handling of 'self.get_repeated_menu_item' methods with no 'request' kwarg
- Rotate deprecation warnings
- Add blank release notes
- Added Tom Dyson to contributors list
- Fixed a type in docs

Housekeeping to start work on Wagtailmenus 2.50

---

docs/source/releases/2.5.0a.rst
wagtailmenus/managers.py
wagtailmenus/models/menuitems.py
wagtailmenus/models/menus.py

Fixes #167 
As well as updating `MenuWithMenuItems.top_level_items` to utilise `Menu.get_base_page_queryset()`, I also needed to make some alterations to `MenuItemManager.for_display()` to ensure that 'get_base_page_queryset' is the only part of the chain responsible for identifying which pages are suitable for display. Having the filtering done twice (in `MenuItemManager.for_display()` AND `Menu.get_base_page_queryset()`) is not only needlessly expensive, but could potentially be confusing if developers want 'get_base_page_queryset' to include pages that 'for_display' excludes.

'get_base_page_queryset' method is solely responsible for filtering out unsuitable pages from menus

---

CHANGELOG.md
CONTRIBUTORS.md
docs/source/releases/2.5.0a.rst
docs/source/rendering_menus/template_tag_reference.rst
wagtailmenus/templatetags/menu_tags.py

* Attribute order for `get_sub_menu_items_for_page()` has changed, and the following arguments are now required:
* original_menu_tag (previously optional)
* current_level (previously optional)
* max_levels (previously optional)
* Any code calling`get_sub_menu_items_for_page()` now does so with arguments in a consistent order
* Attribute order for `prime_menu_items()` has changed, and the following new arguments are now required (needed for implementation of hooks):
* parent_page
* current_level
* max_levels
* `prime_menu_items()` no longer accepts the `check_for_children` argument (instead, `current_level` and `max_levels` are used to work out a new `stop_at_this_level` boolean variable)
* Any code calling `prime_menu_items()` always creates a `menu_items` variable, which is then added to …

Tidying up of menu_tags.py

---

CHANGELOG.md
docs/source/advanced_topics/hooks.rst
docs/source/advanced_topics/index.rst
docs/source/releases/2.5.0a.rst
wagtailmenus/models/menus.py
wagtailmenus/templatetags/menu_tags.py
wagtailmenus/tests/test_hooks.py

Fixes #159.
While wagtailmenus has long supported the use of custom classes for most things (allowing developers to override methods as they see fit), for a long time, I've felt that it should be easier to override some core/shared behaviour without the technical overhead of having to create and maintain multiple custom models and classes.
This PR adds support for several 'hooks' to allow behaviour to be customised more easily. 
The documentation explains what each hook does and provides some example implementations to copy from.

Add 'hooks' to allow behaviour to be customised more easiliy

---

.travis.yml
CHANGELOG.md
README.rst
docs/source/index.rst
docs/source/releases/2.5.0a.rst
tox.ini

Add tox test environment to test codebase with wagtail 1.12 and update bits in readme and docs that specify wagtail version support.

Add support for Wagtail 1.12

---

CHANGELOG.md
docs/source/advanced_topics/hooks.rst
docs/source/installation.rst
docs/source/releases/2.5.0a.rst
wagtailmenus/management/commands/autopopulate_main_menus.py
wagtailmenus/models/menus.py
wagtailmenus/tests/test_commands.py
wagtailmenus/tests/test_models.py

Adds an `autopopulate_main_menus` command that can be run as part of the installation process to help populate main menus based on the 'home' and 'section root' level pages for each site.
The above command utilises a new `add_menu_items_for_pages()` method on the `MenuWithMenuItems` class, which converts a `PageQuerySet` into menu items

Fix: #164 Add a management command to populate main menus from existing page tree

---

wagtailmenus/templatetags/menu_tags.py

All menu templates currently work by creating a copy of the current context, then updating the copy with new values before rendering it. I think the tags were originally developed with a misunderstanding about what 'context' is, and treating it as a dictionary. 
Since we only need the data from the current `Context` object, and not any other part of it, we should simplify the code by using `context.flatten()` to create a dictionary, update the the dictionary as required with new values, then create a new Context object from that dictionary to use for rendering.
This will also help with #89, as it seems that context objects themselves are immutable when using Jinja2.

Don't copy entire Context objects for template tags when all that is needed is their data 

---

wagtailmenus/models/menus.py

When you set `LANGUAGE_CODE` in Django's _settings.py_ to anything but `"en"`, the next time you ran `python manage.py makemigrations` it created a new migration **inside the wagtailmenus app** like this:
```
/usr/local/lib/python3.6/site-packages/wagtailmenus/migrations/0023_auto_20171023_1200.py
- Alter field max_levels on flatmenu
- Alter field use_specific on flatmenu
- Alter field max_levels on mainmenu
- Alter field use_specific on mainmenu
```
The reason was that the `help_text` for `max_levels` and `use_specific` contains HTML markup and thus was wrapped in `mark_safe()`. The result of this was that the originally lazy translation string was **not lazy anymore** but evaluated (and translated) while the file was parsed. In our case this lead to a migration with these four …

Prevent unnecessary creation of migrations when not using `"en"` as the main language in Django

---

CHANGELOG.md
docs/source/releases/2.6.0.rst
wagtailmenus/app_settings.py
wagtailmenus/models/menus.py
wagtailmenus/models/mixins.py
wagtailmenus/tests/test_menu_rendering.py

Follows the approach outlined in #194 to make some recent changes fully backwards compatible

Make template engine neutrality changes backwards-compatible

---

docs/source/releases/2.6.0a.rst

Designate 2.6 as LTS release and announce dropping of Python 2 support

---

.travis.yml
CHANGELOG.md
README.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/releases/2.7.0a.rst
setup.py
tox.ini
wagtailmenus/forms.py
wagtailmenus/management/commands/autopopulate_main_menus.py
wagtailmenus/models/menuitems.py
wagtailmenus/models/menus.py
wagtailmenus/models/pages.py
wagtailmenus/panels.py
wagtailmenus/settings/base.py
wagtailmenus/templatetags/menu_tags.py
wagtailmenus/tests/models/menus.py
wagtailmenus/tests/models/pages.py
wagtailmenus/tests/test_backend.py
wagtailmenus/tests/test_commands.py
wagtailmenus/tests/test_custom_models.py
wagtailmenus/tests/test_hooks.py
wagtailmenus/tests/test_menu_classes.py
wagtailmenus/tests/test_menu_rendering.py
wagtailmenus/tests/test_page_models.py
wagtailmenus/tests/urls.py
wagtailmenus/utils/misc.py
wagtailmenus/views.py
wagtailmenus/wagtail_hooks.py

Tests are currently passing against the beta release with both Django 1.11 and 2.0.
I don't envisage there being any changes between now and the official release, but I'd like to wait and be sure before merging.
It's unknown at this time whether wagtail-condensedinlinepanel will be updated to support 2.0 any time soon, so I might add a note about that to the installation instructions where it is recommended.

Adds support for Wagtail 2.0 and Django 2.0 

---

wagtailmenus/forms.py

This really small fix prevents to have the `handle` field label untranslated when it is replaced by a `ChoiceField`.
Thanks by the way for this nice extension!

Keep the 'handle' field label when switching to ChoiceField

---

docs/source/releases/2.8.0.rst
wagtailmenus/models/menus.py
wagtailmenus/utils/deprecation.py

Fix #222: Deprecate the current active class attribution logic for 'custom URL' menu items

---

docs/source/advanced_topics/hooks.rst

Fixed display of example tree in docs.

---

setup.py
wagtailmenus/models/menus.py
wagtailmenus/tests/test_backend.py
wagtailmenus/tests/test_custom_models.py
wagtailmenus/tests/test_flatmenu_class.py
wagtailmenus/tests/test_mainmenu_class.py

- Replaces `get_menu_items_manager()` on `AbstractMainMenu` and `AbstractFlatMenu` with a generic implmentation on `MenuWithMenuItems`
- In `MenuWithMenuItems.get_top_level_items()` eliminate the unnecessary 'values_list()' when fetching page data, and only make additional queries if at least one menu items links to a page
- In `AbstractFlatMenu.get_for_site()` only ever use a single query to identify a suitable menu instance (instead of a potential 3)

General tidying and optimisation

---

wagtailmenus/models/menus.py

Create a more convenient reference to self.request at the top of Menu.prime_menu_items() and use throughout to reduce line lengths

Minor tidying in Menu.prime_menu_items()

---

docs/source/installation.rst
setup.py
tox.ini
wagtailmenus/tests/test_backend.py

Restore wagtail-condensedinlinepanel integration tests now that a Wagtail.2.0 compatible version has been released

---

docs/source/releases/2.10.0.rst
wagtailmenus/__init__.py
wagtailmenus/app_settings.py
wagtailmenus/constants.py
wagtailmenus/context_processors.py
wagtailmenus/forms.py
wagtailmenus/management/commands/autopopulate_main_menus.py
wagtailmenus/models/menuitems.py
wagtailmenus/models/menus.py
wagtailmenus/models/pages.py
wagtailmenus/panels.py
wagtailmenus/templates/wagtailmenus/includes/header.html
wagtailmenus/templates/wagtailmenus/includes/header_with_site_switcher.html
wagtailmenus/templates/wagtailmenus/mainmenu_edit.html
wagtailmenus/templatetags/menu_tags.py
wagtailmenus/tests/test_commands.py
wagtailmenus/tests/test_custom_models.py
wagtailmenus/tests/test_mainmenu_class.py
wagtailmenus/tests/test_menu_items.py
wagtailmenus/tests/utils.py
wagtailmenus/utils/conf.py
wagtailmenus/views.py
wagtailmenus/wagtail_hooks.py

- Move constants to their own module, rather than throwing them in with other settings
- Overrides `__getattr__` on AppSettings class to provide 'attribute like' references to settings without having to define a new property method for each one
- Default setting values are defined together in a single, simple dictionary
- Adds 'get_class' and 'get_model' methods to AppSettings class to provide a more sensible way to fetch python classes or django models referenced by settings

Improvements to 'app settings' implementation

---

docs/source/releases/2.11.0.rst
docs/source/releases/index.rst
runtests.py
wagtailmenus/__init__.py
wagtailmenus/utils/deprecation.py

- Bump version to, and add release notes for 2.11a
- Cycle deprecation warnings and remove anything that needs removing (nothing this time)
- Update runtests.py command while here, to make test options and output more useful

Housekeeping for 2.11a

---

wagtailmenus/models/menus.py

- `max_levels` and `use_specific` are always set when an object is initialised, so a class attribute is unsuitable for those.
- `request` should only ever be specific to an object too, and so doesn't make sense as a class attribute.

Remove request, max_levels and use_specific class attributes from Menu

---

wagtailmenus/models/menus.py

The value of 'use_specific' in hook kwargs should match `self.use_specific`, not `self.max_levels`

Fix typo in Menu.get_common_hook_kwargs()

---

wagtailmenus/models/menus.py

- Alter the signature of Menu.render_from_tag() to give an indication of common expected/supported arguments.
- Override render_from_tag() for each menu class so that the signature indicates how the supported arguments vary for each menu type.

Menu class code readability improvements

---

wagtailmenus/utils/deprecation.py

Rename deprecation warning classes to indicate that the version after v2.13 will be v3.0

Rename deprecation warning classes

---

CHANGELOG.md
wagtailmenus/models/menus.py
wagtailmenus/tests/models/menus.py
wagtailmenus/tests/test_custom_models.py
wagtailmenus/tests/test_mainmenu_class.py
wagtailmenus/tests/test_sectionmenu_class.py

- Renames `Menu.get_contextual_vals_from_context()` to `Menu._create_contextualvals_obj_from_context()` to better indicate what the method does.
- Renames `Menu.get_option_vals_from_options()` to `Menu._create_optionvals_obj_from_values()` to better indicate what the method does.
- Replaces `Menu.get_instance_for_rendering()` with two new methods: 
-  `Menu.get_from_collected_values()` - which is used when the menu class extends django.db.models.Model,
- And `Menu.create_from_collected_values()`

Menu method renaming

---

wagtailmenus/models/menus.py

Breaks responsibility for getting/creating an appropriate menu object and calling it's prepare_to_render() method out into a separate method: `_get_render_prepared_object()`. This will help with future planned developments, such as rendering menus as JSON instead of to a template.

Split menu object preparation and rendering into separate methods

---

wagtailmenus/panels.py

Panel heading typo fix: "Rendering setings" -> "Render settings"

---

CHANGELOG.md
docs/source/releases/2.13.rst
wagtailmenus/models/menus.py
wagtailmenus/models/pages.py
wagtailmenus/tests/test_menu_class.py

If menus items happen to be being recursively generated based on whether `menuitem.sub_menu` is set instead of whether `menuitem.has_children_in_menu` is True, this can result in an an infinite loop when MenuPage objects copy themselves to add a duplicate into a sub menu (because the sub_menu from the parent get's copied to the child).
These changes ensure items only come out of `_prime_menu_item()` with a `sub_menu` added if it was intentionally added by that method.

Safeguarding against infinite loops when using 'menuitem.sub_menu'

---

CHANGELOG.md
docs/source/releases/2.13.rst
wagtailmenus/models/menus.py

Update SectionMenu to augment `self.root_page` with menuitem-like attributes in `prepare_to_render()` instead of overriding `get_context_data()` in the unusual way that it does. 
Not only does this correct a bit of general design awkwardness, but will also ensure the `root_page` is augmented consistently in cases where 'get_context_data()' might not be run (e.g. if the data were being rendered as JSON in an API, instead of to a template)

Tidy 'root_page' augmentation logic in SectionMenu

---

wagtailmenus/models/menus.py

The code is self-explanatory enough that the comment is redundant, and there's no need to create a 'current_page' variable if it's needed in the conditional part below

Minor tidying in SectionMenu.prepare_to_render()

---

CONTRIBUTORS.md
wagtailmenus/models/pages.py

In Wagtail 2.2 Page.get_sitemap_urls() can accept the optional request argument.
Currently, sites with `AbstractLinkPage`s are unable to generate a sitemap.
https://docs.wagtail.io/en/v2.2.2/releases/2.2.html#page-get-sitemap-urls-now-accepts-an-optional-request-keyword-argument
This is a minor change that won't cause any issues with older Wagtail installs so I haven't included any unit tests but I'm happy to add if you need them.

Update Page.get_sitemap_urls() signature to match Wagtail 2.2

---

CONTRIBUTORS.md
setup.py
wagtailmenus/models/menus.py

Fixes #354 by removing the six import and use.
Should make wagtail 2.8 compatible (with django 3.0.x).

Remove six dependency

---

docs/source/advanced_topics/hooks.rst
docs/source/installation.rst
docs/source/overview.rst
docs/source/releases/3.0.2.rst
docs/source/rendering_menus/custom_templates.rst
docs/source/rendering_menus/template_tag_reference.rst
docs/source/settings_reference.rst

- Show examples of page-powered multi-level menus in overview and make more of an effort to explain how `Page.show_in_menus` and `Page.live` affect output (related: #335 #353 ) 
- Clarify that menu items will not be shown when overriding the `WAGTAILMENUS_FLAT_MENUS_EDITABLE_IN_WAGTAILADMIN` and `WAGTAILMENUS_MAIN_MENUS_EDITABLE_IN_WAGTAILADMIN` settings (replaces #365 )
- Improve template examples for making use of `item.sub_menu` (related: #363 )
- Include `{% load menu_tags %}` in all template examples where it would be required (resolves #362)
- Use correct unicode characters for tree examples instead of the standard pipe character
- Various other minor formatting corrections

Minor documentation improvements

---

docs/source/advanced_topics/custom_menu_classes.rst
docs/source/installation.rst
docs/source/settings_reference.rst

Some confusion from people recently using wagtailmenus led to creating a settings.py file
ref https://docs.wagtail.io/en/v2.9/reference/project_template.html?highlight=base.py#django-settings

Wagtail splits the settings out to base, dev, and prod

---

docs/source/advanced_topics/custom_menu_classes.rst
docs/source/advanced_topics/hooks.rst
docs/source/menupage.rst
docs/source/overview.rst
docs/source/releases/2.4.0.rst

I've updated the documentation to match the module path changes made in Wagtail 2.0.
https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/docs/releases/2.0.rst#wagtail-module-path-updates
I left the reference to `wagtailcore` in the `2.1.2` release notes since the module path was accurate at the time though happy to update that too.
https://github.com/rkhleics/wagtailmenus/blob/master/docs/source/releases/2.1.2.rst
Additionally, I've fixed an issue in the hook example code. Happy to break out into a separate PR if you prefer.
Thanks!

Update wagtail imports

---

docs/source/installation.rst

In version 3.0.2 at least, the `=True` part isn't recognized and generates an error:
```
$ python manage.py autopopulate_main_menus --add-home-links=True
usage: manage.py autopopulate_main_menus [-h] [--add-home-links] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color] [--force-color] [--skip-checks]
manage.py autopopulate_main_menus: error: argument --add-home-links: ignored explicit argument 'True'
```

Fix autopopulate_main_menus instructions

---

wagtailmenus/templates/menus/flat_menu.html

The default template does not currently honor the `show_menu_heading` parameter.
The `show_menu_heading` setting works as documented.
- Suppress `menu_heading` for templates if `show_menu_heading = True`. This is more in line with defensive programming practices, but it could break existing implementations relying on the buggy behavior.

Fix show_menu_heading for default flat menus

---

wagtailmenus/apps.py
wagtailmenus/templatetags/menu_tags.py

Fixes #452 and #435 
Sets DEFAULT_AUTO_FIELD explicitly to use the 'django.db.models.AutoField' field.

👌 IMPROVE: Set default_auto_field explicitly

---

docs/source/installation.rst
setup.py
tox.ini
wagtailmenus/conf/tests/test_modeladmin_disable_settings.py
wagtailmenus/modeladmin.py
wagtailmenus/settings/base.py
wagtailmenus/views.py
wagtailmenus/wagtail_hooks.py

This PR extend compatibility of `wagtailmenus` to Wagtail 5.1 and particularly supports the newly independent `wagtail_modeladmin` module in lieu of the previous `wagtail.contrib.modeladmin` module.
This is a stop-gap measure to provide clean support for Wagtail 5.1 while a more permanent Snippet-based solution is developed. There is no change in functionality. Tests have been extended to Wagtail 5.1 and all pass. Packaging and documentation have also been updated.
See #459 for discussion.

Independent wagtail_modeladmin support for Wagtail 5.1

---

.github/workflows/test.yml

according to:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

👷: update set-output command

---

.github/workflows/bandit.yml

GitHub security suggests a code scanner, I think bandit is fine.

🔒: add bandit code scanner

---

wagtailmenus/locale/de/LC_MESSAGES/django.po

"Link zu" (German for "link to") requires dative, not accusative.

fix German typo

---

CHANGELOG.md
CONTRIBUTORS.md
docs/source/releases/4.0.1.rst
docs/source/releases/4.0.2.rst
docs/source/releases/index.rst
setup.py
wagtailmenus/__init__.py
wagtailmenus/locale/ar/LC_MESSAGES/django.po
wagtailmenus/locale/de/LC_MESSAGES/django.po
wagtailmenus/locale/en/LC_MESSAGES/django.po
wagtailmenus/locale/es_419/LC_MESSAGES/django.po
wagtailmenus/locale/fr/LC_MESSAGES/django.po
wagtailmenus/locale/id/LC_MESSAGES/django.po
wagtailmenus/locale/it/LC_MESSAGES/django.po
wagtailmenus/locale/lt/LC_MESSAGES/django.po
wagtailmenus/locale/nl/LC_MESSAGES/django.po
wagtailmenus/locale/pt_BR/LC_MESSAGES/django.po
wagtailmenus/locale/ru/LC_MESSAGES/django.po
wagtailmenus/locale/uk/LC_MESSAGES/django.po
wagtailmenus/locale/zh_CN/LC_MESSAGES/django.po

Update the version to 4.0.2, add release notes for this version, and fix missing release notes for 4.0.1. 
Bonus:
- Update source translation files
- Add Python 3.13 to PyPI classifiers

Bump version to 4.0.2 and update release notes

---

.github/workflows/release.yml
CHANGELOG.md
README.rst
docs/source/index.rst
tox.ini

The changes primarily focus on updating the supported versions of Python, Django, and Wagtail, and removing support for older versions and adding some Wagtail version compatibility conditionals.
[tox.ini](https://github.com/jazzband/wagtailmenus/pull/509/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449): Updated test matrix for Wagtail 6.4
[README.rst](https://github.com/jazzband/wagtailmenus/pull/509/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168f) and [docs/source/index.rst](https://github.com/jazzband/wagtailmenus/pull/509/files#diff-4eec6cec5f6fab1548b85433ea8ca81315ae165db4b7f84019f287df9015699f): Updated compatibility information to reflect the removal of Python 3.8 and Django 3.2, and the addition of Django 5.1 and Python 3.11. …

Wagtail 6.4 updates
