jazzband/wagtailmenus

CONTRIBUTING.md
CONTRIBUTORS.md
requirements.txt
tox.ini

Add CONTRIBUTING.md to outline the contribution process / requirements

---

wagtailmenus/templatetags/menu_tags.py

Use SECTION_ROOT_DEPTH in prime_menu_items

---

.gitignore
wagtailmenus/wagtail_hooks.py

Related to #22 
Include the site and other useful info on the listing page for flat menus

Improve admin listing for FlatMenus

---

CHANGELOG.md
wagtailmenus/migrations/0001_initial.py
wagtailmenus/migrations/0008_auto_20160131_2327.py
wagtailmenus/migrations/0012_auto_20160419_0039.py
wagtailmenus/migrations/0016_auto_20160930_0645.py
wagtailmenus/models.py
wagtailmenus/tests/test_backend.py

Unicode compatibility for Python 2.7 and adding missing strings for translation

---

.gitignore
wagtailmenus/locale/fr/LC_MESSAGES/django.po

Hi, 
According to your previous message, I've just committed the french locale files.
You ignore .po files in .gitignore, I think it should be nice to adds them because you'll redistribute them in pypi.  I've added pycharm (my IDE) files in the .gitignore.
Thanks !

Adds french translation files

---

CONTRIBUTORS.md
wagtailmenus/locale/it/LC_MESSAGES/django.po

Locale 'it' added

---

wagtailmenus/__init__.py
wagtailmenus/app_settings.py
wagtailmenus/apps.py
wagtailmenus/templatetags/menu_tags.py
wagtailmenus/utils/misc.py
wagtailmenus/utils/template.py
wagtailmenus/utils/version.py
wagtailmenus/wagtail_hooks.py

- Update the app_settings module to define an AppSettings instance, then replace the whole module with that instance
- Move custom model finding login to AppSetting class
- Add nicer version definition
- Split utils into utils.misc and utils.template
- Add utils.version for help with nicer version definition

App settings refactor

---

.travis.yml
wagtailmenus/tests/migrations/0014_noabsoluteurlspage.py
wagtailmenus/tests/test_custom_models.py

Fixes #149
Also tweaked some Travis config settings in an attempt to speed build speed when testing

Fix reference to wagtailcore migration in test migrations 

---

setup.py
wagtailmenus/__init__.py
wagtailmenus/models/pages.py

Apply the fix from issue #152 and bump version

Prep for v2.1.4 bug fix release

---

MANIFEST.in
wagtailmenus/__init__.py
wagtailmenus/models/pages.py

Apply the fix from issue #152 and bump version to 2.2.2

Prep for v2.2.2 bug fix release

---

MANIFEST.in
wagtailmenus/__init__.py
wagtailmenus/models/pages.py

Apply the fix from issue #152 and bump version to 2.3.2

Prep for v2.3.2 bug fix release

---

runtests.py

Fix submitted by @obestwalter to my fork, so resubmitting here to the original repo.
Fixes #170

Fix: Travis builds are no longer failing when tests fail

---

setup.py

Remove duplicate Django 1.11 classifier

---

CONTRIBUTORS.md
wagtailmenus/models/menus.py
wagtailmenus/models/mixins.py

Reverts rkhleics/wagtailmenus#190

Revert "Make Menu.get_template neutral to template engine"

---

CONTRIBUTORS.md
wagtailmenus/models/menus.py
wagtailmenus/models/mixins.py

Reverts rkhleics/wagtailmenus#191

Restore "Make Menu.get_template neutral to template engine"

---

.travis.yml
CHANGELOG.md
README.rst
docs/source/index.rst
docs/source/releases/2.6.0a.rst
tox.ini

Make compatible with Wagtail 1.13

---

CHANGELOG.md
docs/source/releases/2.7.0a.rst

- Adds compatibility related change details to latest release notes
- Brings changelog up to date

2.7.0 release note updates

---

CHANGELOG.md
docs/source/releases/2.7.1.rst
docs/source/releases/index.rst
wagtailmenus/__init__.py

- Update CHANGELOG
- Add 2.7.1 release notes
- Bump version

Release prep for 2.7.1

---

setup.py

Fix django-cogwheels to 0.2

---

wagtailmenus/models/menus.py

- Rewrite 'menu item priming logic' to improve readability
- Add new comments
- Update prime_menu_items() to return a generator once more

Add a Menu.prime_menu_item() method, that primes only a single item

---

.travis.yml
CHANGELOG.md
README.rst
docs/source/index.rst
docs/source/releases/2.13.rst
setup.py
tox.ini

Adds support for Wagtail 2.3 and Django 2.1

---

.travis.yml
README.rst
docs/source/index.rst
setup.py
tox.ini

Add / announce support for Wagtail 2.4

---

CONTRIBUTORS.md
docs/source/advanced_topics/custom_menu_classes.rst
docs/source/installation.rst

small documentation changes

---

wagtailmenus/panels.py

Respect the WAGTAILMENUS_USE_CONDENSEDINLINEPANEL setting

---

CHANGELOG.md
docs/source/releases/3.1.rst
wagtailmenus/errors.py
wagtailmenus/models/menus.py
wagtailmenus/tests/test_base_menu_classes.py
wagtailmenus/utils/misc.py
wagtailmenus/utils/tests/test_misc.py

Fix: Fail gracefully when request missing from context

---

CHANGELOG.md
docs/source/releases/3.1.1.rst
docs/source/releases/3.1.rst
docs/source/releases/index.rst
wagtailmenus/__init__.py

As described in https://github.com/jazzband/wagtailmenus/blob/master/docs/source/contributing/packaging_releases.rst

Bumped to version 3.1.1 and updated release notes

---

.github/workflows/test.yml

See [deprecation notice](https://github.com/marketplace/actions/codecov)

fix: update codecov Action to v3 -- v1 deprecated

---

wagtailmenus/models/menus.py

Had to merge upstream main branch for #442

I18n compatibility

---

wagtailmenus/development/urls.py.example

fix: replace outdated url function with path function in dev urls.py

---

docs/source/advanced_topics/hooks.rst

`is_authenticated` is attribute and not function
https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#attributes

Doc: small fix in hooks.rst

---

CHANGELOG.md
docs/source/index.rst

🐛 FIX: Versions on docs index

---

CHANGELOG.md
docs/source/releases/3.1.9.rst
docs/source/releases/index.rst
wagtailmenus/__init__.py
wagtailmenus/locale/en/LC_MESSAGES/django.po

- Changelog updates
- Translations update

Release prep/3.1.9

---

.github/workflows/release.yml

sorry @MrCordeiro i'm gonna take the liberty to merge this one w/o review 😉

👷 (ci): update release GH Action syntax
